name: "Paul's blog"
description: "My personal blog"

port: 3000
production: true
url: "http://blog.pdostal.cz"

#paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

exclude: ["Gemfile*"]

assets:
  cache: true
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors/normalize
