name: "Paul's blog"
description: "My personal blog"

port: 3000
production: false
url: "http://0.0.0.0:3000"

#paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: pygments

exclude: ["bootstrap/docs", "font-awesome/src", "config/", "lib/", "tmp/"]

assets:
  cache: false
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors/normalize
